baseURL = "https://golvartv.online/"
languageCode = "tr"
title = "Yılan Oyunu – Google Yılan Oyunu Oyna | Ücretsiz Yılan Oyunları"
theme = "Mango"

# Disable default taxonomies to avoid warnings
disableKinds = ["taxonomy", "term"]

[params]
  description = ""
  keywords = ""

[menu]
  [[menu.main]]
    name = "🏠 Anasayfa"
    url = "/"
    weight = 1
  [[menu.main]]
   name = "Nasıl Oynanır"
    url = "/Nasıl Oynanır/"
    weight = 2
  [[menu.main]]
    name = "İletişim"
    url = "/İletişim/"
    weight = 3